// Texts for the Leads and CRM tabs (owner and sales), in the office's three languages.
import { useT } from "./context";

type Dict = Record<string, string>;
const en: Dict = {
  "l.sources": "Sources",
  "l.sourcesHow": "Each source is read as often as it changes. New and changed projects appear here by themselves.",
  "l.src.ryhti": "Building permits (Ryhti, SYKE)",
  "l.src.street": "Street permits for sites (City of Helsinki)",
  "l.src.notices": "Permit notices (Lupapiste)",
  "l.src.prh": "Housing companies and property managers (PRH)",
  "l.every": "every {h} h",
  "l.lastRun": "last run {t}",
  "l.never": "not run yet",
  "l.nextRun": "next {t}",
  "l.found": "{n} found",
  "l.failed": "failed: {e}",
  "l.running": "Updating…",
  "l.updateNow": "Update now",
  "l.updateStarted": "Update started – the list refreshes when it's done.",
  "l.autoOn": "Automatic updates on",
  "l.autoOff": "Automatic updates off",
  "l.lastBuild": "{total} projects, {added} new in the last update",
  "l.search": "Search address, company or manager",
  "l.mine": "Mine",
  "l.showDone": "Show closed",
  "l.prio.all": "All",
  "l.prio.high": "High",
  "l.prio.medium": "Medium",
  "l.prio.low": "Low",
  "l.prio.hold": "On hold",
  "l.none": "No projects match",
  "l.noneText": "Change the filters, or update the sources.",
  "l.empty": "No projects yet",
  "l.emptyText": "Run the first update: the platform reads the permit and site sources and builds the list.",
  "l.tier.A": "Renovation, block of flats",
  "l.tier.B": "New build",
  "l.tier.C": "House",
  "l.tier.S": "Site permit only",
  "l.tier.L": "Permit notice",
  "l.timing.upcoming": "Starts {d}",
  "l.timing.active": "On site until {d}",
  "l.timing.ending": "Ending {d}",
  "l.timing.ended": "Site ended",
  "l.timing.permit": "Permit {d}, not started",
  "l.timing.started": "Permit {d}, started",
  "l.rel.confirmed": "Exterior work confirmed",
  "l.rel.likely": "Scaffolding likely",
  "l.rel.possible": "Possible",
  "l.rel.unknown": "Scope unknown",
  "l.rel.unlikely": "Interior work",
  "l.scope.scaffold": "scaffolds",
  "l.scope.facade": "facade",
  "l.scope.roof": "roof",
  "l.scope.balcony": "balconies",
  "l.scope.windows": "windows",
  "l.scope.extension": "extension",
  "l.scope.lifting": "lifting",
  "l.scope.new_build": "new build",
  "l.why.starts_soon": "Site work about to start",
  "l.why.site_running": "Site running now",
  "l.why.site_ending": "Site ending soon",
  "l.why.exterior_permit": "Exterior permit, not started",
  "l.why.scope_unknown": "Permit without a work description",
  "l.why.old_permit": "Permit over 8 months old",
  "l.why.homeowner": "Homeowner – letter only, no cold calls",
  "l.why.interior_only": "Permit notice says interior work",
  "l.why.site_ended": "Site work has ended",
  "l.why.company_check": "Housing company match is uncertain",
  "l.why.scaffold_in_place": "Scaffolds already up – contractor relationship, later phases",
  "l.why.facade_survey": "Facade survey – renovation likely in 1–2 years",
  "l.why.lift_only": "Work from a lift – no scaffolding",
  "l.why.new_build": "New build",
  "l.why.extension_permit": "Extension permit – may be inside (attic, basement)",
  "l.rel.future": "Coming (survey)",
  "l.rel.lift_only": "Lift work",
  "l.contact.ready": "Contact details",
  "l.contact.name_only": "Manager known, no contact details",
  "l.contact.missing": "Buyer unknown",
  "l.st.new": "New",
  "l.st.researching": "Researching",
  "l.st.contacted": "Contacted",
  "l.st.meeting": "Meeting",
  "l.st.quoted": "Quoted",
  "l.st.won": "Won",
  "l.st.lost": "Lost",
  "l.st.not_relevant": "Not relevant",
  "l.newBadge": "New",
  "l.gone": "No longer in sources",
  "l.next": "Next: {a}",
  "l.unassigned": "Unassigned",
  "l.status": "Status",
  "l.assignee": "Owner",
  "l.priority": "Priority",
  "l.priorityAuto": "Automatic ({p})",
  "l.nextAction": "Next step",
  "l.nextDate": "Date",
  "l.save": "Save",
  "l.saved": "Saved.",
  "l.whyTitle": "Why this priority",
  "l.ask": "What to ask",
  "l.ask.site": "The site is running or about to start. Ask who the main contractor is and whether scaffolding is arranged for every phase – offer a quote or backup capacity.",
  "l.ask.permit": "The permit is decided but work hasn't started. Ask whether the renovation is tendered, when it starts, and whether scaffolding can be a separate line in the tender.",
  "l.ask.unknown": "Check first what the permit is for (facade, roof, balconies or interior) – ask the property manager about the plan and schedule.",
  "l.ask.newbuild": "New build: ask the developer or main contractor about the frame and facade phase, and offer a facade scaffolding package.",
  "l.ask.house": "Homeowner: send a letter with the instant online quote. No calls or text messages to consumers.",
  "l.facts": "Project",
  "l.f.type": "Work and building",
  "l.f.built": "Built",
  "l.f.apartments": "Apartments",
  "l.f.buildings": "Buildings",
  "l.f.floors": "Floors",
  "l.f.decided": "Permit decided",
  "l.f.permits": "Permit IDs",
  "l.f.property": "Property",
  "l.f.protected": "Protected building",
  "l.f.map": "Show on map",
  "l.street": "Street permits for the site",
  "l.streetNone": "No street permit for these addresses.",
  "l.notices": "Permit notices",
  "l.research": "Research",
  "l.r.scope": "Scope",
  "l.r.timing": "Timing",
  "l.r.buyer": "Who buys",
  "l.r.route": "Contact route",
  "l.r.question": "First question",
  "l.r.gaps": "Not confirmed",
  "l.r.evidence": "Evidence",
  "l.r.checked": "checked {d}",
  "l.orgs": "Organisations",
  "l.org.housing": "Housing company",
  "l.org.manager": "Property manager",
  "l.org.contractor": "Main contractor",
  "l.org.owner": "Owner / developer",
  "l.org.none": "Not linked",
  "l.org.link": "Link",
  "l.org.change": "Change",
  "l.org.unlink": "Unlink",
  "l.org.open": "Open in CRM",
  "l.org.pick": "Find an organisation",
  "l.org.create": "New: {name}",
  "l.org.noContact": "No contact details yet – add them in the CRM.",
  "l.prh": "PRH register",
  "l.prhUncertain": "Same street name exists in another town – check before contacting.",
  "l.notes": "Notes and history",
  "l.notePh": "Call notes, what was agreed, who to contact…",
  "l.addNote": "Add note",
  "l.statusChanged": "Status → {s}",
  "l.drafts": "Message drafts (Finnish)",
  "l.draft.manager": "To the property manager",
  "l.draft.contractor": "To the main contractor",
  "l.copy": "Copy",
  "l.copied": "Copied.",
  "l.close": "Close",
  "l.count": "{n} projects",
  "c.new": "New organisation",
  "c.search": "Search name, business ID, email",
  "c.all": "All",
  "c.type.property_manager": "Property manager",
  "c.type.housing_company": "Housing company",
  "c.type.contractor": "Contractor",
  "c.type.developer": "Developer",
  "c.type.public_owner": "Public owner",
  "c.type.client": "Client",
  "c.type.partner": "Partner",
  "c.type.other": "Other",
  "c.stage.none": "–",
  "c.stage.prospect": "Prospect",
  "c.stage.contacted": "Contacted",
  "c.stage.active": "Active client",
  "c.stage.partner": "Partner",
  "c.stage.inactive": "Inactive",
  "c.none": "No organisations yet",
  "c.noneText": "Organisations come in from the lead sources (housing companies and their managers), or add your own clients and partners.",
  "c.noMatch": "Nothing matches",
  "c.contacts": "{n} contacts",
  "c.prospects": "{n} projects",
  "c.fromRegistry": "From PRH",
  "c.name": "Name",
  "c.type": "Type",
  "c.stage": "Stage",
  "c.businessId": "Business ID",
  "c.website": "Website",
  "c.email": "Email (company)",
  "c.phone": "Phone (company)",
  "c.address": "Address",
  "c.notes": "Notes",
  "c.tags": "Tags (comma separated)",
  "c.account": "Business customer account",
  "c.accountNone": "Not linked",
  "c.saved": "Saved.",
  "c.created": "Organisation added.",
  "c.edit": "Edit details",
  "c.noDetails": "No business ID or contact details yet – add them with Edit details.",
  "c.people": "People",
  "c.peopleNone": "No people yet. Add the property manager or the person handling renovations.",
  "c.addPerson": "Add person",
  "c.editPerson": "Edit person",
  "c.p.name": "Name",
  "c.p.role": "Role",
  "c.p.email": "Email",
  "c.p.phone": "Phone",
  "c.p.note": "Note",
  "c.p.primary": "Main contact",
  "c.p.removed": "Person removed.",
  "c.p.remove": "Remove",
  "c.activity": "Activity",
  "c.activityPh": "Meeting, call, agreement…",
  "c.addActivity": "Add",
  "c.related": "Related organisations",
  "c.linked": "Projects",
  "c.linkedNone": "No projects linked.",
  "c.delete": "Delete organisation",
  "c.deleteTitle": "Delete {name}?",
  "c.deleteText": "Its people and notes are deleted and the projects lose the link. This can't be undone.",
  "c.deleted": "Organisation deleted.",
  "c.duplicate": "This organisation is already in the CRM.",
  "c.privacy": "Store business contact details only, for this business purpose. Don't save private persons' details without a reason.",
  "c.cancel": "Cancel",
  "c.save": "Save"
};
const fi: Dict = {
  "l.sources": "Lähteet",
  "l.sourcesHow": "Jokainen lähde luetaan niin usein kuin se päivittyy. Uudet ja muuttuneet hankkeet tulevat listalle itsestään.",
  "l.src.ryhti": "Rakennusluvat (Ryhti, SYKE)",
  "l.src.street": "Työmaiden aluevuokraukset (Helsingin kaupunki)",
  "l.src.notices": "Lupapäätösten kuulutukset (Lupapiste)",
  "l.src.prh": "Taloyhtiöt ja isännöitsijät (PRH)",
  "l.every": "{h} h välein",
  "l.lastRun": "luettu {t}",
  "l.never": "ei vielä luettu",
  "l.nextRun": "seuraava {t}",
  "l.found": "{n} löytyi",
  "l.failed": "epäonnistui: {e}",
  "l.running": "Päivitetään…",
  "l.updateNow": "Päivitä nyt",
  "l.updateStarted": "Päivitys alkoi – lista päivittyy, kun se on valmis.",
  "l.autoOn": "Automaattinen päivitys päällä",
  "l.autoOff": "Automaattinen päivitys pois",
  "l.lastBuild": "{total} hanketta, {added} uutta viime päivityksessä",
  "l.search": "Hae osoitetta, yhtiötä tai isännöitsijää",
  "l.mine": "Omat",
  "l.showDone": "Näytä suljetut",
  "l.prio.all": "Kaikki",
  "l.prio.high": "Kiireelliset",
  "l.prio.medium": "Keskitaso",
  "l.prio.low": "Matala",
  "l.prio.hold": "Odottaa",
  "l.none": "Ei osumia",
  "l.noneText": "Muuta suodattimia tai päivitä lähteet.",
  "l.empty": "Ei vielä hankkeita",
  "l.emptyText": "Aja ensimmäinen päivitys: alusta lukee lupa- ja työmaalähteet ja kokoaa listan.",
  "l.tier.A": "Korjaushanke, kerrostalo",
  "l.tier.B": "Uudisrakennus",
  "l.tier.C": "Pientalo",
  "l.tier.S": "Vain aluevuokraus",
  "l.tier.L": "Lupakuulutus",
  "l.timing.upcoming": "Alkaa {d}",
  "l.timing.active": "Työmaa {d} asti",
  "l.timing.ending": "Päättyy {d}",
  "l.timing.ended": "Työmaa päättynyt",
  "l.timing.permit": "Lupa {d}, ei aloitettu",
  "l.timing.started": "Lupa {d}, aloitettu",
  "l.rel.confirmed": "Ulkopuolinen työ varmistettu",
  "l.rel.likely": "Telineet todennäköisiä",
  "l.rel.possible": "Mahdollinen",
  "l.rel.unknown": "Laajuus ei tiedossa",
  "l.rel.unlikely": "Sisätyö",
  "l.scope.scaffold": "telineet",
  "l.scope.facade": "julkisivu",
  "l.scope.roof": "katto",
  "l.scope.balcony": "parvekkeet",
  "l.scope.windows": "ikkunat",
  "l.scope.extension": "laajennus",
  "l.scope.lifting": "nostot",
  "l.scope.new_build": "uudiskohde",
  "l.why.starts_soon": "Työmaa alkamassa",
  "l.why.site_running": "Työmaa käynnissä",
  "l.why.site_ending": "Työmaa päättymässä",
  "l.why.exterior_permit": "Ulkopuolinen lupa, ei aloitettu",
  "l.why.scope_unknown": "Luvassa ei työn kuvausta",
  "l.why.old_permit": "Lupa yli 8 kk vanha",
  "l.why.homeowner": "Kuluttaja – vain kirje, ei puhelinmyyntiä",
  "l.why.interior_only": "Kuulutuksen mukaan sisätyö",
  "l.why.site_ended": "Työmaa on päättynyt",
  "l.why.company_check": "Taloyhtiön tunnistus epävarma",
  "l.why.scaffold_in_place": "Telineet jo pystyssä – urakoitsijasuhde, myöhemmät vaiheet",
  "l.why.facade_survey": "Julkisivututkimus – remontti todennäköinen 1–2 vuoden sisällä",
  "l.why.lift_only": "Nostintyö – ei telineitä",
  "l.why.new_build": "Uudiskohde",
  "l.why.extension_permit": "Laajennuslupa – voi olla sisällä (ullakko, kellari)",
  "l.rel.future": "Tulossa (tutkimus)",
  "l.rel.lift_only": "Nostintyö",
  "l.contact.ready": "Yhteystiedot",
  "l.contact.name_only": "Isännöitsijä tiedossa, ei yhteystietoja",
  "l.contact.missing": "Ostaja ei tiedossa",
  "l.st.new": "Uusi",
  "l.st.researching": "Selvitetään",
  "l.st.contacted": "Yhteys otettu",
  "l.st.meeting": "Tapaaminen",
  "l.st.quoted": "Tarjottu",
  "l.st.won": "Voitettu",
  "l.st.lost": "Hävitty",
  "l.st.not_relevant": "Ei relevantti",
  "l.newBadge": "Uusi",
  "l.gone": "Ei enää lähteissä",
  "l.next": "Seuraavaksi: {a}",
  "l.unassigned": "Ei vastuuhenkilöä",
  "l.status": "Tila",
  "l.assignee": "Vastuuhenkilö",
  "l.priority": "Prioriteetti",
  "l.priorityAuto": "Automaattinen ({p})",
  "l.nextAction": "Seuraava toimenpide",
  "l.nextDate": "Päivä",
  "l.save": "Tallenna",
  "l.saved": "Tallennettu.",
  "l.whyTitle": "Miksi tämä prioriteetti",
  "l.ask": "Mitä kysyä",
  "l.ask.site": "Työmaa on käynnissä tai alkamassa. Kysy, kuka on pääurakoitsija ja onko telineet sovittu kaikkiin vaiheisiin – tarjoa tarjous tai varakapasiteettia.",
  "l.ask.permit": "Lupa on myönnetty, mutta työ ei ole alkanut. Kysy, onko remontti kilpailutettu, milloin se alkaa ja voiko telineet olla oma rivinsä tarjouspyynnössä.",
  "l.ask.unknown": "Selvitä ensin, mitä lupa koskee (julkisivu, katto, parvekkeet vai sisätyö) – kysy isännöitsijältä suunnitelmasta ja aikataulusta.",
  "l.ask.newbuild": "Uudiskohde: kysy rakennuttajalta tai pääurakoitsijalta runko- ja julkisivuvaiheesta ja tarjoa julkisivutelinepakettia.",
  "l.ask.house": "Kuluttaja: lähetä kirje, jossa on linkki pikatarjoukseen. Ei puheluita eikä tekstiviestejä kuluttajille.",
  "l.facts": "Hanke",
  "l.f.type": "Työ ja rakennus",
  "l.f.built": "Valmistunut",
  "l.f.apartments": "Asuntoja",
  "l.f.buildings": "Rakennuksia",
  "l.f.floors": "Kerroksia",
  "l.f.decided": "Lupapäätös",
  "l.f.permits": "Lupatunnukset",
  "l.f.property": "Kiinteistö",
  "l.f.protected": "Suojeltu rakennus",
  "l.f.map": "Näytä kartalla",
  "l.street": "Työmaan aluevuokraukset",
  "l.streetNone": "Ei aluevuokrausta näille osoitteille.",
  "l.notices": "Lupakuulutukset",
  "l.research": "Selvitys",
  "l.r.scope": "Laajuus",
  "l.r.timing": "Aikataulu",
  "l.r.buyer": "Kuka ostaa",
  "l.r.route": "Yhteydenottotapa",
  "l.r.question": "Ensimmäinen kysymys",
  "l.r.gaps": "Vahvistamatta",
  "l.r.evidence": "Lähteet",
  "l.r.checked": "tarkistettu {d}",
  "l.orgs": "Organisaatiot",
  "l.org.housing": "Taloyhtiö",
  "l.org.manager": "Isännöitsijä",
  "l.org.contractor": "Pääurakoitsija",
  "l.org.owner": "Omistaja / rakennuttaja",
  "l.org.none": "Ei liitetty",
  "l.org.link": "Liitä",
  "l.org.change": "Vaihda",
  "l.org.unlink": "Poista liitos",
  "l.org.open": "Avaa asiakkuuksissa",
  "l.org.pick": "Hae organisaatio",
  "l.org.create": "Uusi: {name}",
  "l.org.noContact": "Ei vielä yhteystietoja – lisää ne asiakkuuksiin.",
  "l.prh": "PRH-rekisteri",
  "l.prhUncertain": "Samanniminen katu on myös toisessa kunnassa – tarkista ennen yhteydenottoa.",
  "l.notes": "Muistiinpanot ja historia",
  "l.notePh": "Puhelun muistiinpanot, mitä sovittiin, kenelle soittaa…",
  "l.addNote": "Lisää muistiinpano",
  "l.statusChanged": "Tila → {s}",
  "l.drafts": "Viestipohjat",
  "l.draft.manager": "Isännöitsijälle",
  "l.draft.contractor": "Pääurakoitsijalle",
  "l.copy": "Kopioi",
  "l.copied": "Kopioitu.",
  "l.close": "Sulje",
  "l.count": "{n} hanketta",
  "c.new": "Uusi organisaatio",
  "c.search": "Hae nimeä, Y-tunnusta, sähköpostia",
  "c.all": "Kaikki",
  "c.type.property_manager": "Isännöitsijä",
  "c.type.housing_company": "Taloyhtiö",
  "c.type.contractor": "Urakoitsija",
  "c.type.developer": "Rakennuttaja",
  "c.type.public_owner": "Julkinen omistaja",
  "c.type.client": "Asiakas",
  "c.type.partner": "Kumppani",
  "c.type.other": "Muu",
  "c.stage.none": "–",
  "c.stage.prospect": "Prospekti",
  "c.stage.contacted": "Yhteys otettu",
  "c.stage.active": "Aktiivinen asiakas",
  "c.stage.partner": "Kumppani",
  "c.stage.inactive": "Ei aktiivinen",
  "c.none": "Ei vielä organisaatioita",
  "c.noneText": "Organisaatiot tulevat liidilähteistä (taloyhtiöt ja niiden isännöitsijät), tai lisää omat asiakkaat ja kumppanit.",
  "c.noMatch": "Ei osumia",
  "c.contacts": "{n} henkilöä",
  "c.prospects": "{n} hanketta",
  "c.fromRegistry": "PRH:sta",
  "c.name": "Nimi",
  "c.type": "Tyyppi",
  "c.stage": "Vaihe",
  "c.businessId": "Y-tunnus",
  "c.website": "Verkkosivu",
  "c.email": "Sähköposti (yritys)",
  "c.phone": "Puhelin (yritys)",
  "c.address": "Osoite",
  "c.notes": "Muistiinpanot",
  "c.tags": "Tunnisteet (pilkulla eroteltuna)",
  "c.account": "Yritysasiakastili",
  "c.accountNone": "Ei liitetty",
  "c.saved": "Tallennettu.",
  "c.created": "Organisaatio lisätty.",
  "c.edit": "Muokkaa tietoja",
  "c.noDetails": "Ei vielä Y-tunnusta eikä yhteystietoja – lisää ne kohdasta Muokkaa tietoja.",
  "c.people": "Henkilöt",
  "c.peopleNone": "Ei vielä henkilöitä. Lisää isännöitsijä tai korjaushankkeista vastaava henkilö.",
  "c.addPerson": "Lisää henkilö",
  "c.editPerson": "Muokkaa henkilöä",
  "c.p.name": "Nimi",
  "c.p.role": "Rooli",
  "c.p.email": "Sähköposti",
  "c.p.phone": "Puhelin",
  "c.p.note": "Huomio",
  "c.p.primary": "Pääyhteyshenkilö",
  "c.p.removed": "Henkilö poistettu.",
  "c.p.remove": "Poista",
  "c.activity": "Tapahtumat",
  "c.activityPh": "Tapaaminen, puhelu, sopimus…",
  "c.addActivity": "Lisää",
  "c.related": "Liittyvät organisaatiot",
  "c.linked": "Hankkeet",
  "c.linkedNone": "Ei liitettyjä hankkeita.",
  "c.delete": "Poista organisaatio",
  "c.deleteTitle": "Poistetaanko {name}?",
  "c.deleteText": "Henkilöt ja muistiinpanot poistetaan ja hankkeet menettävät liitoksen. Tätä ei voi perua.",
  "c.deleted": "Organisaatio poistettu.",
  "c.duplicate": "Organisaatio on jo asiakkuuksissa.",
  "c.privacy": "Tallenna vain yritysten yhteystietoja tähän liiketoimintatarkoitukseen. Älä tallenna yksityishenkilöiden tietoja ilman syytä.",
  "c.cancel": "Peruuta",
  "c.save": "Tallenna"
};
const ru: Dict = {
  ...en,
  "l.sources": "Источники",
  "l.sourcesHow": "Каждый источник читается так часто, как он обновляется. Новые проекты появляются сами.",
  "l.updateNow": "Обновить",
  "l.running": "Обновление…",
  "l.search": "Адрес, компания или управляющий",
  "l.mine": "Мои",
  "l.prio.all": "Все",
  "l.prio.high": "Высокий",
  "l.prio.medium": "Средний",
  "l.prio.low": "Низкий",
  "l.prio.hold": "Ожидание",
  "l.status": "Статус",
  "l.assignee": "Ответственный",
  "l.priority": "Приоритет",
  "l.nextAction": "Следующий шаг",
  "l.nextDate": "Дата",
  "l.save": "Сохранить",
  "l.saved": "Сохранено.",
  "l.notes": "Заметки и история",
  "l.addNote": "Добавить заметку",
  "l.close": "Закрыть",
  "c.new": "Новая организация",
  "c.search": "Название, Y-tunnus, email",
  "c.all": "Все",
  "c.type.property_manager": "Управляющая компания",
  "c.type.housing_company": "Жилищное общество",
  "c.type.contractor": "Подрядчик",
  "c.type.developer": "Застройщик",
  "c.type.public_owner": "Гос. владелец",
  "c.type.client": "Клиент",
  "c.type.partner": "Партнёр",
  "c.type.other": "Другое",
  "c.people": "Люди",
  "c.addPerson": "Добавить человека",
  "c.save": "Сохранить",
  "c.cancel": "Отмена"
};
const DICTS: Record<string, Dict> = { en, fi, ru };

/** Sales texts in the office language: st("l.timing.upcoming", { d: "12.10." }). */
export function useST() {
  const { lang } = useT();
  const d = DICTS[lang] || en;
  return (key: string, vars?: Record<string, string | number>) => {
    let s = d[key] ?? en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
    return s;
  };
}
